# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
src = "contracts"
out = "out"
script = "script"
libs = ["lib"]
evm_version = "shanghai"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10
solc = "0.7.6"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "base64-sol/=lib/base64/"
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
hyperliquid_testnet = "https://api.hyperliquid-testnet.xyz/evm"
arbitrum_sepolia = "https://arbitrum-sepolia.gateway.tenderly.co"
